### ISSUE TITLE
No address associated with hostname

### ISSUE THREAD

**Issue by sms1sis** [mishakorzik/Ultra-DDos#4]
Enter Target URL: https://shikho.com/                                                                     Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Ultra-DDos/src/Url.py", line 25, in <module>
    ip = socket.gethostbyname(target)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 7] No address associated with hostname

**Comment by mishakorzik** [comment]
Website didn't work.

**Comment by sms1sis** [comment]
ok.Only IP works...
